name: CI

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Send Compile action
      if: startsWith(github.ref, 'refs/tags/') != true && github.ref != 'refs/heads/master'
      run: |
        export DISPATCH_ACTION="$(echo run_build)"
        echo "::set-env name=NEW_DISPATCH_ACTION::$DISPATCH_ACTION"
    
    - name: Send Release action
      if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
      run: |
        export DISPATCH_ACTION="$(echo run_release)"
        echo "::set-env name=NEW_DISPATCH_ACTION::$DISPATCH_ACTION"

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: ${{ github.repository_owner }}/orbis-sysroot
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: ${{ env.NEW_DISPATCH_ACTION }}
        client-payload: '{"ref": "${{ github.ref }}"}'